/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx,md}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary': '#ffffff',
        'primary-fixed': '#d6e4f9',
        'error-container': '#ffdad6',
        'secondary-fixed': '#d1e4ff',
        'on-primary-fixed': '#0f1c2c',
        'surface-container': '#edeeea',
        'surface-container-highest': '#e2e3df',
        'outline-variant': '#c4c6cc',
        'on-tertiary-container': '#a17f3b',
        'error': '#ba1a1a',
        'on-primary': '#ffffff',
        'on-secondary-container': '#48617e',
        'on-tertiary-fixed-variant': '#5d4201',
        'on-background': '#1a1c1a',
        'background': '#f9faf5',
        'on-surface-variant': '#44474c',
        'on-secondary-fixed': '#001d36',
        'outline': '#74777d',
        'on-error': '#ffffff',
        'on-tertiary-fixed': '#261900',
        'on-error-container': '#93000a',
        'secondary-fixed-dim': '#afc9ea',
        'surface-variant': '#e2e3df',
        'on-secondary': '#ffffff',
        'surface-dim': '#d9dad6',
        'surface-bright': '#f9faf5',
        'surface-container-lowest': '#ffffff',
        'inverse-surface': '#2f312e',
        'tertiary-container': '#261900',
        'on-secondary-fixed-variant': '#2f4865',
        'on-primary-container': '#778598',
        'primary-fixed-dim': '#bac8dc',
        'inverse-on-surface': '#f0f1ed',
        'secondary-container': '#c2dcff',
        'tertiary': '#000000',
        'surface-container-low': '#f3f4f0',
        'secondary': '#47607e',
        'surface-container-high': '#e8e8e4',
        'surface': '#f9faf5',
        'on-surface': '#1a1c1a',
        'primary-container': '#0f1c2c',
        'on-primary-fixed-variant': '#3a4859',
        'tertiary-fixed-dim': '#e9c176',
        'brand-navy': '#263040',
        'brand-navy-light': '#344050',
        'brand-orange': '#BA4C12',
        'brand-orange-dark': '#9A3D1A',
        'primary': '#000000',
        'surface-tint': '#525f71',
        'tertiary-fixed': '#ffdea5',
        'inverse-primary': '#bac8dc',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Newsreader', 'serif'],
        serif: ['Cormorant Garamond', 'serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
        sans: ['Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
